#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaboWebApi
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="RaboBank")]
	public partial class CustomerTableDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCustomerTable(CustomerTable instance);
    partial void UpdateCustomerTable(CustomerTable instance);
    partial void DeleteCustomerTable(CustomerTable instance);
    #endregion
		
		public CustomerTableDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["RaboBankConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerTableDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerTableDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerTableDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CustomerTableDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CustomerTable> CustomerTables
		{
			get
			{
				return this.GetTable<CustomerTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CustomerTable")]
	public partial class CustomerTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Cid;
		
		private string _CName;
		
		private System.Nullable<System.DateTime> _CDOB;
		
		private string _CAddress;
		
		private string _CCity;
		
		private string _CState;
		
		private System.Nullable<int> _CPin;
		
		private string _CTelephone;
		
		private string _CEmail;
		
		private System.Nullable<System.DateTime> _CreatedDate;
		
		private System.Nullable<System.DateTime> _EditedDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCidChanging(int value);
    partial void OnCidChanged();
    partial void OnCNameChanging(string value);
    partial void OnCNameChanged();
    partial void OnCDOBChanging(System.Nullable<System.DateTime> value);
    partial void OnCDOBChanged();
    partial void OnCAddressChanging(string value);
    partial void OnCAddressChanged();
    partial void OnCCityChanging(string value);
    partial void OnCCityChanged();
    partial void OnCStateChanging(string value);
    partial void OnCStateChanged();
    partial void OnCPinChanging(System.Nullable<int> value);
    partial void OnCPinChanged();
    partial void OnCTelephoneChanging(string value);
    partial void OnCTelephoneChanged();
    partial void OnCEmailChanging(string value);
    partial void OnCEmailChanged();
    partial void OnCreatedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedDateChanged();
    partial void OnEditedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnEditedDateChanged();
    #endregion
		
		public CustomerTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cid", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Cid
		{
			get
			{
				return this._Cid;
			}
			set
			{
				if ((this._Cid != value))
				{
					this.OnCidChanging(value);
					this.SendPropertyChanging();
					this._Cid = value;
					this.SendPropertyChanged("Cid");
					this.OnCidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CName", DbType="VarChar(30)")]
		public string CName
		{
			get
			{
				return this._CName;
			}
			set
			{
				if ((this._CName != value))
				{
					this.OnCNameChanging(value);
					this.SendPropertyChanging();
					this._CName = value;
					this.SendPropertyChanged("CName");
					this.OnCNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CDOB", DbType="Date")]
		public System.Nullable<System.DateTime> CDOB
		{
			get
			{
				return this._CDOB;
			}
			set
			{
				if ((this._CDOB != value))
				{
					this.OnCDOBChanging(value);
					this.SendPropertyChanging();
					this._CDOB = value;
					this.SendPropertyChanged("CDOB");
					this.OnCDOBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAddress", DbType="VarChar(MAX)")]
		public string CAddress
		{
			get
			{
				return this._CAddress;
			}
			set
			{
				if ((this._CAddress != value))
				{
					this.OnCAddressChanging(value);
					this.SendPropertyChanging();
					this._CAddress = value;
					this.SendPropertyChanged("CAddress");
					this.OnCAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CCity", DbType="VarChar(20)")]
		public string CCity
		{
			get
			{
				return this._CCity;
			}
			set
			{
				if ((this._CCity != value))
				{
					this.OnCCityChanging(value);
					this.SendPropertyChanging();
					this._CCity = value;
					this.SendPropertyChanged("CCity");
					this.OnCCityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CState", DbType="VarChar(20)")]
		public string CState
		{
			get
			{
				return this._CState;
			}
			set
			{
				if ((this._CState != value))
				{
					this.OnCStateChanging(value);
					this.SendPropertyChanging();
					this._CState = value;
					this.SendPropertyChanged("CState");
					this.OnCStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CPin", DbType="Int")]
		public System.Nullable<int> CPin
		{
			get
			{
				return this._CPin;
			}
			set
			{
				if ((this._CPin != value))
				{
					this.OnCPinChanging(value);
					this.SendPropertyChanging();
					this._CPin = value;
					this.SendPropertyChanged("CPin");
					this.OnCPinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CTelephone", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CTelephone
		{
			get
			{
				return this._CTelephone;
			}
			set
			{
				if ((this._CTelephone != value))
				{
					this.OnCTelephoneChanging(value);
					this.SendPropertyChanging();
					this._CTelephone = value;
					this.SendPropertyChanged("CTelephone");
					this.OnCTelephoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEmail", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string CEmail
		{
			get
			{
				return this._CEmail;
			}
			set
			{
				if ((this._CEmail != value))
				{
					this.OnCEmailChanging(value);
					this.SendPropertyChanging();
					this._CEmail = value;
					this.SendPropertyChanged("CEmail");
					this.OnCEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedDate
		{
			get
			{
				return this._CreatedDate;
			}
			set
			{
				if ((this._CreatedDate != value))
				{
					this.OnCreatedDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedDate = value;
					this.SendPropertyChanged("CreatedDate");
					this.OnCreatedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EditedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> EditedDate
		{
			get
			{
				return this._EditedDate;
			}
			set
			{
				if ((this._EditedDate != value))
				{
					this.OnEditedDateChanging(value);
					this.SendPropertyChanging();
					this._EditedDate = value;
					this.SendPropertyChanged("EditedDate");
					this.OnEditedDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
