<?xml version="1.0" encoding="utf-8"?><Database Name="RaboBank" Class="UserLoginDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=desktop-b3mtsd3\shubham;Initial Catalog=RaboBank;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="RaboBankConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.UserTable" Member="UserTables">
    <Type Name="UserTable">
      <Column Name="Uid" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="Custid" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>